services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpasswd
    ports:
      - "5432:5432"
    networks:
      - kong-net

  kong:
    image: kong/kong-gateway:3.3.0.0
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpasswd
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PORTAL_GUI_HOST: localhost:8003
      KONG_PORTAL: on
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    depends_on:
      - kong-database
    networks:
      - kong-net
    command: kong migrations bootstrap

  konga:
    image: pantsel/konga:latest
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: kongpasswd
      DB_DATABASE: kong
    ports:
      - "1337:1337"
    depends_on:
      - kong
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
